[variables]
PHP_VERSION = "8.3"

[phases.setup]
nixPkgs = ["php83Extensions.intl", "php83Extensions.zip"]

[phases.install]
cmds = [
    "composer install --optimize-autoloader --no-dev --ignore-platform-req=ext-intl --ignore-platform-req=ext-zip"
]

[phases.build]
cmds = [
    "npm ci && npm run build"
]

[start]
cmd = "php artisan config:cache && php artisan route:cache && php artisan view:cache && php artisan migrate --force && php artisan storage:link && php artisan serve --host=0.0.0.0 --port=$PORT"
