[phases.setup]
aptPkgs = ["..."]

[phases.install]
cmds = [
    "pecl install redis",
    "docker-php-ext-enable redis",
    "docker-php-ext-install intl",
    "docker-php-ext-install zip",
    "docker-php-ext-install pdo_pgsql",
    "docker-php-ext-install bcmath",
    "docker-php-ext-install gd",
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
